#!/usr/bin/env python
"""
Generar URL de prueba actualizada con JavaScript mejorado
"""

print("🔧 JAVASCRIPT MEJORADO - NUEVA PRUEBA")
print("=" * 40)
print("")
print("📝 Se agregaron mejoras a JavaScript:")
print("   ✅ waitForOptionsAndLoadState() - espera opciones cargadas")
print("   ✅ Logs detallados en consola del navegador")
print("   ✅ Verificación robusta de timing")
print("")
print("🌐 PROBAR EN NAVEGADOR:")
print("   1. Abrir: http://localhost:8000/admin/invoicing/invoice/99/change/")
print("   2. Abrir consola navegador (F12)")
print("   3. Recargar página (F5)")
print("   4. Verificar logs en consola")
print("")
print("✅ DEBE MOSTRAR:")
print("   - 'Transferencia' seleccionada")
print("   - Campo 'Cuenta' oculto")
print("   - Selector 'Cuenta Bancaria' con 'PICHINCHA - ****9377' PRE-SELECCIONADO")
print("   - Observaciones cargadas en textarea")
print("")
print("🔍 LOGS EN CONSOLA DEBEN MOSTRAR:")
print("   - '✅ Opciones cargadas, procediendo con loadInitialState'")
print("   - '✅ Cuenta bancaria pre-seleccionada: PICHINCHA - ...'")
print("   - '✅ Chart Account ID coincidente: 39'")
print("")
print("❌ SI SIGUE FALLANDO, verificar:")
print("   - ¿Las opciones se cargan correctamente?")
print("   - ¿El dataset.chartAccountId está presente?")
print("   - ¿El valor se asigna pero no se muestra?")