# Generated by Django 4.2.7 on 2025-09-28 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('trade_name', models.CharField(max_length=200, verbose_name='Nombre comercial')),
                ('legal_name', models.CharField(max_length=300, verbose_name='Razón social')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('establishment_code', models.CharField(default='001', max_length=3, verbose_name='Código de establecimiento')),
                ('emission_point', models.CharField(default='001', max_length=3, verbose_name='Punto de emisión')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('fiscal_year_start', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], default=1, verbose_name='Mes de inicio del ejercicio fiscal')),
                ('sri_environment', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente SRI')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificado digital (.p12)')),
                ('certificate_password', models.CharField(blank=True, max_length=100, verbose_name='Contraseña del certificado')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Moneda base')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(choices=[('PN', 'Persona Natural'), ('SA', 'Sociedad Anónima'), ('CL', 'Compañía de Responsabilidad Limitada'), ('SC', 'Sociedad Civil')], max_length=2, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Empresa',
                'verbose_name_plural': 'Tipos de Empresa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EconomicActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Código CIIU')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.economicactivity', verbose_name='Actividad padre')),
            ],
            options={
                'verbose_name': 'Actividad Económica',
                'verbose_name_plural': 'Actividades Económicas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('invoice_sequential', models.PositiveIntegerField(default=1, verbose_name='Secuencial de facturas')),
                ('credit_note_sequential', models.PositiveIntegerField(default=1, verbose_name='Secuencial de notas de crédito')),
                ('debit_note_sequential', models.PositiveIntegerField(default=1, verbose_name='Secuencial de notas de débito')),
                ('withholding_sequential', models.PositiveIntegerField(default=1, verbose_name='Secuencial de retenciones')),
                ('decimal_places', models.IntegerField(default=2, verbose_name='Decimales en montos')),
                ('auto_create_entries', models.BooleanField(default=True, verbose_name='Crear asientos automáticamente')),
                ('default_report_format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel')], default='PDF', max_length=10, verbose_name='Formato de reportes por defecto')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.companytype', verbose_name='Tipo de empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies_primary', to='companies.economicactivity', verbose_name='Actividad económica principal'),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_activities',
            field=models.ManyToManyField(blank=True, related_name='companies_secondary', to='companies.economicactivity', verbose_name='Actividades económicas secundarias'),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('accountant', 'Contador'), ('employee', 'Empleado'), ('viewer', 'Solo lectura')], max_length=20, verbose_name='Rol')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='Permisos específicos')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario de Empresa',
                'verbose_name_plural': 'Usuarios de Empresa',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
