# Generated by Django 4.2.7 on 2025-10-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_paymentmethod_company_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="purchase_invoice_sequential",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Secuencial de facturas de compra"
            ),
        ),
    ]
