# Generated by Django 4.2.7 on 2025-10-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('companies', '0003_companysettings_purchase_invoice_sequential'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTaxAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de IVA (%)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts', verbose_name='Cuenta Contable')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Cuenta IVA',
                'verbose_name_plural': 'Configuraciones de Cuentas IVA',
                'ordering': ['tax_rate'],
                'unique_together': {('company', 'tax_rate')},
            },
        ),
    ]
