# Generated by Django 4.2.7 on 2025-10-04 05:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_add_company_tax_account_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_iva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Tasa de IVA que se aplicará por defecto en nuevos productos y facturas. No afecta facturas existentes.', max_digits=5, verbose_name='IVA por defecto (%)'),
        ),
    ]
