# Generated by Django 4.2.7 on 2025-10-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('companies', '0005_add_default_iva_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytaxaccountmapping',
            name='retention_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta específica para retenciones de IVA de esta tarifa', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_retention_mappings', to='accounting.chartofaccounts', verbose_name='Cuenta Retención IVA por Cobrar'),
        ),
        migrations.AlterField(
            model_name='companytaxaccountmapping',
            name='account',
            field=models.ForeignKey(help_text='Cuenta contable para registrar IVA cobrado en ventas', on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts', verbose_name='Cuenta IVA en Ventas'),
        ),
        migrations.CreateModel(
            name='CompanyAccountDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_defaults', to='companies.company', verbose_name='Empresa')),
                ('default_sales_account', models.ForeignKey(blank=True, help_text='Cuenta contable por defecto para registrar ventas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_sales_defaults', to='accounting.chartofaccounts', verbose_name='Cuenta de Ventas por Defecto')),
                ('ir_retention_receivable_account', models.ForeignKey(blank=True, help_text='Cuenta para registrar retenciones de Impuesto a la Renta realizadas por clientes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_ir_retention_defaults', to='accounting.chartofaccounts', verbose_name='Cuenta Retención IR por Cobrar')),
                ('iva_retention_receivable_account', models.ForeignKey(blank=True, help_text='Cuenta para registrar retenciones de IVA realizadas por clientes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_iva_retention_defaults', to='accounting.chartofaccounts', verbose_name='Cuenta Retención IVA por Cobrar')),
            ],
            options={
                'verbose_name': 'Configuración Contable por Defecto',
                'verbose_name_plural': 'Configuraciones Contables por Defecto',
            },
        ),
    ]
