# Generated by Django 4.2.7 on 2025-10-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_change_iva_default_to_15'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='suppliers.purchaseinvoice', verbose_name='Factura de compra origen'),
        ),
    ]
