# Generated by Django 4.2.7 on 2025-09-28 20:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('useful_life_years', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Vida Útil (años)')),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Tasa de Depreciación (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Categoría de Activo',
                'verbose_name_plural': 'Categorías de Activos',
            },
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('responsible_person', models.CharField(blank=True, max_length=100, verbose_name='Persona Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_locations', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Ubicación de Activo',
                'verbose_name_plural': 'Ubicaciones de Activos',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Activo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Activo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción Detallada')),
                ('acquisition_date', models.DateField(verbose_name='Fecha de Adquisición')),
                ('acquisition_method', models.CharField(choices=[('compra', 'Compra'), ('donacion', 'Donación'), ('construccion', 'Construcción Propia'), ('arrendamiento', 'Arrendamiento Financiero'), ('aporte', 'Aporte de Socios')], default='compra', max_length=20, verbose_name='Método de Adquisición')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo de Adquisición')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Depreciación Acumulada')),
                ('book_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor en Libros')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('en_mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio'), ('vendido', 'Vendido'), ('dado_baja', 'Dado de Baja')], default='activo', max_length=20, verbose_name='Estado')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Notas de Condición')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('disposal_reason', models.TextField(blank=True, verbose_name='Motivo de Baja')),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Disposición')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='fixed_assets.assetcategory', verbose_name='Categoría')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located_assets', to='fixed_assets.assetlocation', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'unique_together': {('company', 'asset_code')},
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('lineal', 'Línea Recta'), ('acelerada', 'Acelerada'), ('unidades_produccion', 'Unidades de Producción')], default='lineal', max_length=20, verbose_name='Método de Depreciación')),
                ('useful_life_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Vida Útil (años)')),
                ('useful_life_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Vida Útil (meses)')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor de Salvamento')),
                ('annual_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Depreciación Anual')),
                ('monthly_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Depreciación Mensual')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio Depreciación')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Depreciación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedule', to='fixed_assets.fixedasset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cronograma de Depreciación',
                'verbose_name_plural': 'Cronogramas de Depreciación',
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('maintenance_type', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo'), ('emergencia', 'Emergencia')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('description', models.TextField(verbose_name='Descripción del Mantenimiento')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Mano de Obra')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Repuestos')),
                ('external_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Externo')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Total')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='Proveedor/Técnico')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Garantía Hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fixed_assets.fixedasset', verbose_name='Activo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Activo',
                'verbose_name_plural': 'Mantenimientos de Activos',
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(verbose_name='Año del Período')),
                ('period_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes del Período')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de Depreciación')),
                ('accumulated_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Depreciación Acumulada Anterior')),
                ('accumulated_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Depreciación Acumulada Posterior')),
                ('journal_entry_reference', models.CharField(blank=True, max_length=50, verbose_name='Referencia Asiento Contable')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Contabilizado')),
                ('posting_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Contabilización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='fixed_assets.fixedasset', verbose_name='Activo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_depreciation_entries', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Asiento de Depreciación',
                'verbose_name_plural': 'Asientos de Depreciación',
                'unique_together': {('asset', 'period_year', 'period_month')},
            },
        ),
    ]
