# Generated by Django 4.2.7 on 2025-10-02 05:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("companies", "0002_paymentmethod_company_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_product_has_iva_product_iva_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "supplier_invoice_number",
                    models.CharField(
                        max_length=20, verbose_name="Número de factura del proveedor"
                    ),
                ),
                (
                    "internal_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número interno"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de vencimiento"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("received", "Recibida"),
                            ("validated", "Validada"),
                            ("paid", "Pagada"),
                            ("cancelled", "Anulada"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "payable_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_payable_accounts",
                        to="accounting.chartofaccounts",
                        verbose_name="Cuenta por pagar",
                    ),
                ),
                (
                    "payment_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.paymentmethod",
                        verbose_name="Forma de Pago",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recibido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura de Compra",
                "verbose_name_plural": "Facturas de Compra",
                "ordering": ["-date", "-supplier_invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("natural", "Persona Natural"),
                            ("juridical", "Persona Jurídica"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de proveedor",
                    ),
                ),
                (
                    "identification",
                    models.CharField(max_length=13, verbose_name="Cédula/RUC"),
                ),
                (
                    "trade_name",
                    models.CharField(max_length=200, verbose_name="Nombre comercial"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Razón social"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("address", models.TextField(verbose_name="Dirección")),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Límite de crédito",
                    ),
                ),
                (
                    "payment_terms",
                    models.IntegerField(default=30, verbose_name="Días de pago"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_expense_accounts",
                        to="accounting.chartofaccounts",
                        verbose_name="Cuenta de gastos",
                    ),
                ),
                (
                    "payable_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_payable_accounts",
                        to="accounting.chartofaccounts",
                        verbose_name="Cuenta por pagar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["trade_name"],
                "unique_together": {("company", "identification")},
            },
        ),
        migrations.CreateModel(
            name="PurchaseInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cantidad"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo unitario"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Descuento (%)",
                    ),
                ),
                (
                    "iva_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("12.00"),
                        max_digits=5,
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total línea"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.chartofaccounts",
                        verbose_name="Cuenta contable",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="suppliers.purchaseinvoice",
                        verbose_name="Factura de compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Factura de Compra",
                "verbose_name_plural": "Líneas de Factura de Compra",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="purchaseinvoice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="suppliers.supplier",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseinvoice",
            unique_together={("company", "supplier", "supplier_invoice_number")},
        ),
    ]
