# Generated by Django 4.2.7 on 2025-10-04 03:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ir_retention_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Retención IR'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ir_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención de Impuesto a la Renta', max_digits=5, verbose_name='% Retención IR'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='iva_retention_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Retención IVA'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='iva_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención aplicado al IVA', max_digits=5, verbose_name='% Retención IVA'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de la factura menos las retenciones aplicadas', max_digits=12, verbose_name='Neto a Pagar'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='retention_voucher_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Comprobante Retención'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='retention_voucher_number',
            field=models.CharField(blank=True, help_text='Número del comprobante de retención generado', max_length=20, verbose_name='Núm. Comprobante Retención'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='total_retentions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Retenciones'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ir_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención de Impuesto a la Renta', max_digits=5, verbose_name='Porcentaje retención IR (%)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='iva_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención de IVA según tipo de proveedor', max_digits=5, verbose_name='Porcentaje retención IVA (%)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='retention_agent',
            field=models.BooleanField(default=True, help_text='Si la empresa debe realizar retenciones a este proveedor', verbose_name='Es agente de retención'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sri_classification',
            field=models.CharField(choices=[('persona_natural_no_obligada', 'Persona Natural No Obligada'), ('persona_natural_obligada', 'Persona Natural Obligada'), ('sociedad', 'Sociedad'), ('institucion_publica', 'Institución Pública'), ('regimen_rimpe', 'Régimen RIMPE')], default='sociedad', help_text='Clasificación del proveedor para cálculo automático de retenciones', max_length=30, verbose_name='Clasificación SRI'),
        ),
    ]
