# Generated by Django 4.2.7 on 2025-10-04 05:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_add_retentions_ecuadorian_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='iva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
