# Generated by Django 4.2.7 on 2025-09-29 11:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='iva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5, verbose_name='Tarifa IVA (%)'),
        ),
    ]
