# Generated by Django 4.2.7 on 2025-10-04 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0002_product_has_iva_product_iva_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_cost_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable para el costo de ventas de productos de esta categoría', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_categories', to='accounting.chartofaccounts', verbose_name='Cuenta de costo por defecto'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_inventory_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable para el inventario de productos de esta categoría', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_categories', to='accounting.chartofaccounts', verbose_name='Cuenta de inventario por defecto'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_sales_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable que se usará automáticamente para ventas de productos de esta categoría', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_categories', to='accounting.chartofaccounts', verbose_name='Cuenta de ventas por defecto'),
        ),
    ]
