# Generated by Django 4.2.7 on 2025-09-30 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_alter_invoiceline_product_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='iva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
