# Generated by Django 4.2.7 on 2025-10-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_alter_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_details',
            field=models.TextField(blank=True, help_text='Ingrese los detalles del crédito (plazo, condiciones, etc.)', null=True, verbose_name='Detalles de crédito'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Crédito'), ('transferencia', 'Transferencia')], default='efectivo', max_length=15, verbose_name='Método de pago'),
        ),
    ]
