# Generated by Django 4.2.7 on 2025-10-01 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoicing', '0005_invoice_credit_details_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cash_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable para registro de efectivo', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts', verbose_name='Cuenta de caja'),
        ),
    ]
