# Generated by Django 4.2.7 on 2025-10-01 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoicing', '0006_invoice_cash_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable para registro de crédito a cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_client', to='accounting.chartofaccounts', verbose_name='Cuenta cliente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cash_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable para registro de efectivo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_cash', to='accounting.chartofaccounts', verbose_name='Cuenta de caja'),
        ),
    ]
