# Generated by Django 4.2.7 on 2025-10-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_invoice_client_account_alter_invoice_cash_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cash_account',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client_account',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='credit_details',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
    ]
