# Generated by Django 4.2.7 on 2025-10-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_remove_invoice_cash_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_form',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20, verbose_name='Forma de Pago'),
        ),
    ]
