# Generated by Django 4.2.7 on 2025-10-01 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoicing', '0009_invoice_payment_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts', verbose_name='Cuenta'),
        ),
    ]
