# Generated by Django 4.2.7 on 2025-10-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_make_due_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transfer_detail',
            field=models.TextField(blank=True, verbose_name='Detalle Transferencia'),
        ),
    ]
