# Generated by Django 4.2.7 on 2025-10-02 23:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_invoice_transfer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total línea'),
        ),
    ]
