# Generated by Django 4.2.7 on 2025-10-03 02:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_add_default_line_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock disponible del producto al momento de la venta', max_digits=10, verbose_name='Stock'),
        ),
    ]
