# Generated by Django 4.2.7 on 2025-10-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_add_stock_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date', '-number'], 'permissions': [('change_invoice_status', 'Puede cambiar estado de facturas'), ('mark_invoice_sent', 'Puede marcar facturas como enviadas'), ('mark_invoice_paid', 'Puede marcar facturas como pagadas'), ('mark_invoice_cancelled', 'Puede anular facturas'), ('approve_invoices', 'Puede aprobar facturas'), ('reverse_invoice_entries', 'Puede revertir asientos de facturas')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
