# Generated by Django 4.2.7 on 2025-10-04 15:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_add_invoice_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ir_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención de Impuesto a la Renta', max_digits=5, verbose_name='Porcentaje retención IR (%)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='iva_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención de IVA según tipo de cliente', max_digits=5, verbose_name='Porcentaje retención IVA (%)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='retention_agent',
            field=models.BooleanField(default=False, help_text='Si el cliente debe realizar retenciones en sus compras', verbose_name='Es agente de retención'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sri_classification',
            field=models.CharField(choices=[('persona_natural_no_obligada', 'Persona Natural No Obligada'), ('persona_natural_obligada', 'Persona Natural Obligada'), ('sociedad', 'Sociedad'), ('institucion_publica', 'Institución Pública'), ('regimen_rimpe', 'Régimen RIMPE')], default='sociedad', help_text='Clasificación del cliente para cálculo automático de retenciones', max_length=30, verbose_name='Clasificación SRI'),
        ),
    ]
