# Generated by Django 4.2.7 on 2025-10-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0017_customer_ir_retention_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_observations',
            field=models.TextField(blank=True, help_text='Observaciones adicionales para transferencias bancarias', verbose_name='Observaciones Bancarias'),
        ),
    ]
