# Generated by Django 4.2.7 on 2025-09-28 20:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('civil_status', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión Libre')], default='soltero', max_length=20, verbose_name='Estado Civil')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='Código de Empleado')),
                ('hire_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salario Base')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'En Vacaciones'), ('licencia', 'En Licencia'), ('terminado', 'Terminado')], default='activo', max_length=20, verbose_name='Estado')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Terminación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Categoría de Empleado',
                'verbose_name_plural': 'Categorías de Empleados',
            },
        ),
        migrations.CreateModel(
            name='PayrollConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('concept_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('deduccion', 'Deducción'), ('aporte_empleador', 'Aporte Empleador')], max_length=20, verbose_name='Tipo de Concepto')),
                ('calculation_type', models.CharField(choices=[('fijo', 'Valor Fijo'), ('porcentaje', 'Porcentaje'), ('formula', 'Fórmula')], default='fijo', max_length=20, verbose_name='Tipo de Cálculo')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor Fijo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('affects_iess', models.BooleanField(default=False, verbose_name='Afecta IESS')),
                ('affects_income_tax', models.BooleanField(default=False, verbose_name='Afecta Impuesto a la Renta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_concepts', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'verbose_name_plural': 'Conceptos de Nómina',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Período')),
                ('period_type', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal')], default='mensual', max_length=20, verbose_name='Tipo de Período')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'unique_together': {('company', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Ingresos')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Deducciones')),
                ('total_employer_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Aportes Empleador')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salario Neto')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='companies.company', verbose_name='Empresa')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.employee', verbose_name='Empleado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.payrollperiod', verbose_name='Período')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'unique_together': {('period', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_category_employees', to='payroll.employeecategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_employees', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitario')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_concept_details', to='payroll.payrollconcept', verbose_name='Concepto')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payroll', verbose_name='Nómina')),
            ],
            options={
                'verbose_name': 'Detalle de Nómina',
                'verbose_name_plural': 'Detalles de Nómina',
                'unique_together': {('payroll', 'concept')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'employee_code')},
        ),
    ]
