# Generated by Django 4.2.7 on 2025-10-06 03:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_journalentry_source_purchase_invoice'),
        ('companies', '0006_companytaxaccountmapping_retention_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sbs_code', models.CharField(help_text='Código de la Superintendencia de Bancos del Ecuador', max_length=4, unique=True, verbose_name='Código SBS')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Banco')),
                ('short_name', models.CharField(help_text='Nombre abreviado para mostrar en interfaces', max_length=20, verbose_name='Nombre Corto')),
                ('swift_code', models.CharField(blank=True, help_text='Código SWIFT para transferencias internacionales', max_length=11, verbose_name='Código SWIFT')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('account_type', models.CharField(choices=[('checking', 'Cuenta Corriente'), ('savings', 'Cuenta de Ahorros'), ('credit', 'Tarjeta de Crédito'), ('other', 'Otra')], default='checking', max_length=10, verbose_name='Tipo de Cuenta')),
                ('currency', models.CharField(choices=[('USD', 'Dólares Americanos'), ('EUR', 'Euros'), ('COL', 'Pesos Colombianos')], default='USD', max_length=3, verbose_name='Moneda')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo Inicial')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Apertura')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.bank', verbose_name='Banco')),
                ('chart_account', models.ForeignKey(blank=True, help_text='Vincular con cuenta contable existente (opcional)', limit_choices_to={'aux_type': 'bank'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccounts', verbose_name='Cuenta Contable')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['bank__name', 'account_number'],
                'unique_together': {('company', 'bank', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('transaction_date', models.DateField(verbose_name='Fecha de Transacción')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Fecha Valor')),
                ('transaction_type', models.CharField(choices=[('debit', 'Débito'), ('credit', 'Crédito'), ('transfer_in', 'Transferencia Recibida'), ('transfer_out', 'Transferencia Enviada'), ('fee', 'Comisión Bancaria'), ('interest', 'Interés'), ('other', 'Otro')], max_length=15, verbose_name='Tipo de Transacción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Referencia')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Conciliado')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount', verbose_name='Cuenta Bancaria')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='Asiento Contable')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
