# Generated by Django 4.2.7 on 2025-10-06 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('file', models.FileField(upload_to='extractos_bancarios/%Y/%m/', verbose_name='Archivo del Extracto')),
                ('period_start', models.DateField(verbose_name='Fecha Inicio del Período')),
                ('period_end', models.DateField(verbose_name='Fecha Fin del Período')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Inicial')),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Final')),
                ('status', models.CharField(choices=[('uploaded', 'Cargado'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('reconciled', 'Conciliado'), ('error', 'Error')], default='uploaded', max_length=12, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount', verbose_name='Cuenta Bancaria')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Extracto Bancario',
                'verbose_name_plural': 'Extractos Bancarios',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Conciliado por'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='reconciliation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Conciliación'),
        ),
        migrations.CreateModel(
            name='ExtractoBancarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, max_length=50, verbose_name='Referencia')),
                ('debito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Débito')),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Crédito')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Conciliado')),
                ('extracto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='banking.extractobancario', verbose_name='Extracto')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banktransaction', verbose_name='Transacción Coincidente')),
            ],
            options={
                'verbose_name': 'Detalle de Extracto',
                'verbose_name_plural': 'Detalles de Extracto',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
