# Generated by Django 4.2.7 on 2025-10-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_extractobancario_banktransaction_reconciled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractobancario',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Procesado el'),
        ),
    ]
